### ISSUE TITLE
Error in README.md

### ISSUE THREAD

**Issue by MCMic** [nightsh/i3-plasma#1]
«the config: ln -s $HOME/.i3/config $HOME/.i3/»
This command does not seem possible. You cannot create a link named .i3 when there is a folder with the same name.

**Comment by feute** [comment]
That's not what it means. If you put a folder as a destination that already exists, it will create the symlink with the same filename as the target (`config`). So, in short, it will create a `config` symlink *inside* the `i3` folder.

**Comment by MCMic** [comment]
This was fixed by https://github.com/nightsh/i3-plasma/commit/30c5ce4abbd9067d65bb21e93b03d1facb87f1a2

Source and target pointed to the same file
